language: node_js
node_js:
- lts/*

addons:
  sonarcloud:

install:
- npm i axios
- npm i concurrently
- npm i json-server
- npm i react
- npm i react-router-dom
- npm i -D babel-core
- npm i -D babel-loader
- npm i -D babel-plugin-transform-object-rest-spread
- npm i -D babel-preset-env
- npm i -D babel-preset-react
- npm i -D css-loader
- npm i -D cypress@3.1.0
- npm i -D html-webpack-plugin
- npm i -D style-loader
- npm i -D webpack
- npm i -D nyc
- npm i -D istanbul-instrumenter-loader 
- npm i -D istanbul-lib-coverage
- npm i -D cypress-eslint-preprocessor 
- npm i -D eslint 
- npm i -D cypress-eslint-preprocessor
- npm i -D eslint-config-standard
- npm i -D eslint-plugin-cypress
- npm i -D eslint-plugin-import
- npm i -D eslint-plugin-node
- npm i -D eslint-plugin-promise
- npm i -D  eslint-plugin-standard
#- npm audit fix

before_script:
- npm run dev &

script:
- npm run cypress:run
- sonar-scanner   -Dsonar.projectKey=todo1   -Dsonar.organization=steinko-github   -Dsonar.sources=./src   -Dsonar.host.url=https://sonarcloud.io  -Dsonar.login=b0c0d7ce4ab856b9ebc10a2a6548fa7c58eecc8e

#deploy:
#  provider: releases
#  api_key: "GITHUB OAUTH TOKEN"
#  file: "FILE TO UPLOAD"
# skip_cleanup: true
#  on:
#   tags: true